environments:
  {{ .Environment.Name }}:
    values:
      - ./environments/{{ .Environment.Name }}.yaml.gotmpl

repositories:
  - name: georgedriver
    url: https://georgedriver.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: banzaicloud
    url: https://kubernetes-charts.banzaicloud.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: georgedriver-stable
    url: https://raw.githubusercontent.com/georgedriver/helm-repo-in-github/master/

helmDefaults:
  wait: true
  timeout: 1000
  createNamespace: true

releases:
{{- if .Environment.Values | getOrNil "ingress.enabled" }}
  - name: nginx-ingress
    chart: georgedriver/nginx-ingress-docker-for-mac
    namespace: ingress-nginx
    version: 0.1.1
{{- end }}

{{- if .Environment.Values | getOrNil "cert_manager.enabled" }}
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v0.15.2
    namespace: cert-manager
    set:
      - name: installCRDs
        value: true
{{- end }}

{{- if .Environment.Values | getOrNil "alidns_webhook.enabled" }}
  - name: cert-manager-alidns-webhook
    chart: georgedriver/alidns-webhook
    version: 0.1.0
    namespace: cert-manager
    set:
      - name: alicloud_access_key
        value: {{ .Environment.Values.alidns_webhook.alicloud_access_key }}
      - name: alicloud_secret_key
        value: {{ .Environment.Values.alidns_webhook.alicloud_secret_key }}
      - name: domain
        value: {{ .Environment.Values.alidns_webhook.domain }}
      - name: email
        value: {{ .Environment.Values.alidns_webhook.email }}
    labels:
      depend_on_others: true
{{- end }}

{{- if .Environment.Values | getOrNil "vault.enabled" }}
  - name: vault
    chart: banzaicloud/vault
    version: 1.3.1
    namespace: default
    values:
      - ./values/vault.yaml.gotmpl

  - name: banzaicloud-vault-secrets-webhook
    chart: banzaicloud/vault-secrets-webhook
    version: 1.3.2
    namespace: system-addons
{{- end }}

{{- if .Environment.Values | getOrNil "argocd.enabled" }}
  {{- if .Environment.Values | getOrNil "argocd.git_user" }}
  - name: argo-git-repo-secret
    chart: incubator/raw
    namespace: argocd
    values:
    - templates:
      - |
        apiVersion: v1
        kind: Secret
        metadata:
          name: argo-git-repo-secret
        stringData:
          username: {{ .Environment.Values.argocd.git_user }}
          password: {{ .Environment.Values.argocd.git_token }}
    labels:
      depend_on_others: true
  {{- end }}

  - name: argocd
    chart: argo/argo-cd
    version: 2.3.6
    namespace: argocd
    values:
      - ./values/argocd.yaml.gotmpl
    labels:
      depend_on_others: true
{{- end }}

{{- if .Environment.Values | getOrNil "prometheus_bundles.enabled" }}
  - name: k8s-prometheus-operator
    chart: stable/prometheus-operator
    version: 8.16.1
    namespace: system-monitoring
    values:
      - ./values/k8s-prometheus-operator.yaml.gotmpl

  - name: k8s-prometheus-pushgateway
    chart: stable/prometheus-pushgateway
    version: 1.4.1
    namespace: system-monitoring
    values:
      - ./values/k8s-prometheus-pushgateway.gotmpl

  - name: alert-operator
  # NOTE: Secret from spec targetd configuration is not found: Secret "alertmanager-k8s-prometheus-operator-alertmanager" not found
    chart: georgedriver-stable/alert-operator
    version: 0.1.7
    namespace: system-monitoring
    set:
      - name: image.tag
        value: master-bcd7409

  {{with (readFile "namespaces.values" | fromYaml)}}
  {{range .namespaces}}
  - name: alert-manager-receiver-{{.name}}
    chart: georgedriver-stable/k8s-alert-receiver
    version: 0.1.4
    namespace: {{.name}}
    set:
      - name: target_configuration.name
        value: alertmanager-k8s-prometheus-operator-alertmanager
      - name: target_configuration.namespace
        value: system-monitoring
        {{- if (and (. | getOrNil "slack_channel") (. | getOrNil "slack_webhook"))}}
      - name: slack.name
        value: slack-receiver-{{.name}}
      - name: slack.channel
        value: '{{.slack_channel}}'
      - name:  slack.webhook_url
        value: {{.slack_webhook}}
        {{- end}}
        {{- if (. | getOrNil "pagerduty_integration_key")}}
      - name: pagerduty.name
        value: pagerduty-receiver-{{.name}}
      - name: pagerduty.service_key
        value: {{.pagerduty_integration_key}}
        {{- end}}
    labels:
      depend_on_others: true
  {{end}}
  {{end}}
{{- end }}
