environments:
  k8s-mirana:
    values:
      - ./environments/k8s-mirana.yaml.gotmpl

repositories:
  - name: georgedriver
    url: https://georgedriver.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: banzaicloud
    url: https://kubernetes-charts.banzaicloud.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

helmDefaults:
  wait: true
  args:
      - "--timeout=15m0s"

releases:
{{- if and (.Environment.Values | getOrNil "ingress.enabled") (eq .Environment.Values.cluster.provider "docker-for-mac") }}
  - name: nginx-ingress
    chart: georgedriver/nginx-ingress-docker-for-mac
    namespace: ingress-nginx
    version: 0.1.1
{{- end }}

{{- if .Environment.Values | getOrNil "cert_manager.enabled" }}
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v0.15.1
    namespace: cert-manager
    set:
      - name: installCRDs
        value: true
{{- end }}

{{- if .Environment.Values | getOrNil "alidns_webhook.enabled" }}
  - name: cert-manager-alidns-webhook
    chart: georgedriver/alidns-webhook
    version: 0.1.0
    namespace: cert-manager
    set:
      - name: alicloud_access_key
        value: {{ .Environment.Values.alidns_webhook.alicloud_access_key }}
      - name: alicloud_secret_key
        value: {{ .Environment.Values.alidns_webhook.alicloud_secret_key }}
      - name: domain
        value: {{ .Environment.Values.alidns_webhook.domain }}
      - name: email
        value: {{ .Environment.Values.alidns_webhook.email }}
{{- end }}

{{- if .Environment.Values | getOrNil "vault.enabled" }}
  - name: vault
    chart: banzaicloud/vault
    version: 1.3.1
    namespace: default
    values:
      - ./values/vault.yaml.gotmpl

  - name: banzaicloud-vault-secrets-webhook
    chart: banzaicloud/vault-secrets-webhook
    version: 1.3.2
    namespace: system-addons
{{- end }}

{{- if .Environment.Values | getOrNil "argocd.enabled" }}
  - name: argocd
    chart: argo/argo-cd
    version: 2.3.6
    namespace: argocd
    values:
      - ./values/argocd.yaml.gotmpl
{{- end }}
